name: 2021-tax
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - snakemake=6.6.1
  - pandas>=1.2.4
  - seaborn=0.11.0
  - sourmash>=4.3.0
  - jupyterlab
  - tqdm
  - screed
